#!/usr/bin/env bash

set -euo pipefail

HINTS_DIR="docs/agent-hints"
CONFIG="$HINTS_DIR/_config.yaml"
KIRO_DIR=".kiro/steering"
COPILOT_INSTRUCTIONS=".github/copilot-instructions.md"
COPILOT_SCOPED_DIR=".github/instructions"
GENERATED_HEADER="<!-- DO NOT EDIT — generated by scripts/gen-agent-hints.sh from docs/agent-hints/ -->"
HASH_FILE=".agent-hints-hash"

# ── Hash guard ───────────────────────────────────────────────────────────────
current_hash=$(find "$HINTS_DIR" scripts/gen-agent-hints.sh \
  -type f | sort | xargs sha256sum | sha256sum | cut -d' ' -f1)

if [[ -f "$HASH_FILE" ]] && [[ "$(cat "$HASH_FILE")" == "$current_hash" ]]; then
  echo "⏭  Sources unchanged (hash match). Skipping generation."
  exit 0
fi

# ── Generate ─────────────────────────────────────────────────────────────────
mkdir -p "$KIRO_DIR" "$COPILOT_SCOPED_DIR"

# Wipe previously generated files
rm -f "$KIRO_DIR"/*.md
rm -f "$COPILOT_SCOPED_DIR"/*.instructions.md

# Reset global copilot file
echo "$GENERATED_HEADER" > "$COPILOT_INSTRUCTIONS"
echo "" >> "$COPILOT_INSTRUCTIONS"

count=$(yq '.hints | length' "$CONFIG")

for i in $(seq 0 $((count - 1))); do
  file=$(yq ".hints[$i].file" "$CONFIG")
  title=$(yq ".hints[$i].title" "$CONFIG")
  src="$HINTS_DIR/$file"
  is_global=$(yq ".hints[$i].copilot.global // false" "$CONFIG")

  # ── Kiro ──────────────────────────────────────────────────────────────────
  kiro_inclusion=$(yq ".hints[$i].kiro.inclusion" "$CONFIG")
  kiro_out="$KIRO_DIR/$file"
  {
    echo "$GENERATED_HEADER"
    echo "---"
    echo "inclusion: $kiro_inclusion"
    if [[ "$kiro_inclusion" == "fileMatch" ]]; then
      pattern=$(yq ".hints[$i].kiro.fileMatchPattern" "$CONFIG")
      echo "fileMatchPattern: \"$pattern\""
    fi
    echo "---"
    echo ""
    cat "$src"
  } > "$kiro_out"

  # ── Copilot ────────────────────────────────────────────────────────────────
  if [[ "$is_global" == "true" ]]; then
    # Inline into copilot-instructions.md
    {
      echo "## $title"
      cat "$src"
      echo ""
    } >> "$COPILOT_INSTRUCTIONS"
  else
    apply_to=$(yq ".hints[$i].copilot.applyTo" "$CONFIG")
    copilot_out="$COPILOT_SCOPED_DIR/${file%.md}.instructions.md"
    {
      echo "$GENERATED_HEADER"
      echo "---"
      echo "description: \"$title\""
      echo "applyTo: \"$apply_to\""
      echo "---"
      echo ""
      cat "$src"
    } > "$copilot_out"
  fi
done

# ── Save hash ────────────────────────────────────────────────────────────────
echo "$current_hash" > "$HASH_FILE"

echo "✓ Generated:"
echo "  $KIRO_DIR/ ($(find "$KIRO_DIR" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ') files)"
echo "  $COPILOT_INSTRUCTIONS"
echo "  $COPILOT_SCOPED_DIR/ ($(find "$COPILOT_SCOPED_DIR" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ') files)"
